server:
  port: 9702

spring:
  application:
    name: service_api
  data:
    mongodb:
      host: 6.6.6.6
      port: 27017
      database: yygh
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lyp123
    url: jdbc:mysql://6.6.6.6:3306/yygh_hosp
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev

